version: "3"
services:
  nginx-app:
    # build: 从当前路径构建镜像
    build: .
    ports:
    # nginx默认暴露80端口
      - 4000:80
  learn-nginx:
    build: .
    ports:
      - 4001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html